### ISSUE TITLE
Is there a possibility to color the background as well?

### ISSUE THREAD

**Issue by Prologh** [silkfire/Pastel#1]
Hi!
It might sound like a stupid question, but I don't really know how the ANSI magic is conducted under the hood, so I'll be straightforward.

#### Is there a possibility to color the background as well?

I've discovered your package thanks to [this](https://stackoverflow.com/a/53628050/8065832) StackOverflow answer.

**Comment by silkfire** [comment]
I've added support for background colors a few weeks ago but haven't had time to push the release until now. See the updated readme. The new release should be accepted on NuGet within a few hours.

**Comment by Prologh** [comment]
Awesome! Already tried it and I really, really like it. Thank you for your work.
