### ISSUE TITLE
Colors not showing

### ISSUE THREAD

**Issue by ambujs** [silkfire/Pastel#10]
Hello, why would I get something like this:
![image](https://user-images.githubusercontent.com/1502181/55944536-b7a1b000-5c40-11e9-8277-23bfcd8ef677.png)

Here's my code: 
```Console.WriteLine($"Press {"ENTER".Pastel(Color.FromArgb(165, 229, 250))} to continue");```

It's a netcoreapp2.2 console app.

**Comment by GabrielBBF** [comment]
@ambujs What version of Windows are you using?

**Comment by silkfire** [comment]
@ambujs What version of Windows are you using?

**Comment by ambujs** [comment]
Windows 7.

**Comment by silkfire** [comment]
That explains it. ANSI colors on the Windows platform were introduced by Microsoft starting from Windows 10, version v1511.

**Comment by ambujs** [comment]
ah ok, thanks! I'll close this issue now.

**Comment by silkfire** [comment]
@ambujs That's a limitation unfortunately. I've updated the readme to reflect this more clearly.
