### ISSUE TITLE
Coloring the background

### ISSUE THREAD

**Issue by Asac2142** [silkfire/Pastel#12]
Sorry for asking this but, how can I change the whole background color of the console? 
Something like Console.BackgroundColor = PastelBg("FFD000") ??

**Comment by silkfire** [comment]
That is something you have to do manually in the Console Window options:

![image](https://user-images.githubusercontent.com/1554615/62171963-0fb80b80-b331-11e9-9654-16143b0510b7.png)


This is nothing Pastel should or will change.

**Comment by Asac2142** [comment]
Okay, thank you for answering my question.
Cheers!
