### ISSUE TITLE
Cant use the library

### ISSUE THREAD

**Issue by AsianPotato** [silkfire/Pastel#13]
The type initializer for 'Pastel.ConsoleExtensions' threw an exception.

When trying to do: Console.WriteLine(logstr.Pastel(System.Drawing.Color.DarkRed));

This is on a 64 bit project config, maybe that's the problem

**Comment by GabrielBBF** [comment]
I doubt it has anything to do with Pastel. Could you post the full exception, including the inner one, please?

**Comment by silkfire** [comment]
I doubt it has anything to do with Pastel. Could you post the full exception, including the inner one, please?

**Comment by AsianPotato** [comment]
Yeah my bad, looks like it was a dodgy reference
`System.TypeInitializationException: The type initializer for 'Pastel.ConsoleExtensions' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified`
