### ISSUE TITLE
Console doesn't output correct colors in Debian server (9.9) + SuperPutty

### ISSUE THREAD

**Issue by z3nth10n** [silkfire/Pastel#16]

**Comment by silkfire** [comment]
Could you perhaps provide some more information and maybe some screenshots of what's not working as intended?

**Comment by z3nth10n** [comment]
Hi @silkfire, sorry I was not expecting that quick response.

I'm using your library to output colored messages through the console class, I was using Colorful console, but uses Windows interoperability, so I can't use it on Linux (Debian in my case). I created this to adapt to the Console class:

```
using System;
using System.Drawing;
using Pastel;

#if _WINDOWS

using Console = Colorful.Console;

#else

using Console = System.Console;

#endif

using UConsole = DiscordIdCrawler.Lib.Utils.Console;

namespace DiscordIdCrawler.Lib.Compatibility
{
    using static CompatibilityWorker;

    public static class CompatibleConsole
    {
        public static void WriteLine(object message)
        {
            Console.WriteLine(message?.ToString());
        }

        public static void WriteLine(object message, Color color)
        {
            if (message == null)
            {
                Console.WriteLine();
                return;
            }

            if (IsLinux)
            {
                Console.WriteLine(message.ToString().Pastel(color));
            }
            else
            {
                Console.WriteLine(message.ToString(), color);
            }
        }

        public static void WriteLine(object message, object obj0, object obj1, Color color)
        {
            if (message == null)
            {
                Console.WriteLine();
                return;
            }

            if (IsLinux)
            {
                Console.WriteLine(string.Format(message.ToString(), obj0, obj1).Pastel(color));
            }
            else
            {
                Console.WriteLine(message.ToString(), obj0, obj1, color);
            }
        }

        public static void WriteException<T>(T exception, bool storeOnDB = true, Color color = default)
            where T : Exception
            => UConsole.WriteException(exception, storeOnDB, color);

        public static void WriteException<T>(T exception, string message, bool storeOnDB = true, Color color = default)
            where T : Exception
            => UConsole.WriteException(exception, message, storeOnDB, color);

        #region "Another methods for Linux"

        public static void Write(object message)
        {
            Console.Write(message);
        }

        public static ConsoleKeyInfo ReadKey()
        {
            return Console.ReadKey();
        }

        public static string ReadLine()
        {
            return Console.ReadLine();
        }

        #endregion "Another methods for Linux"
    }
}

But when I try to use (for example): `CompatibleConsole.WriteLine("example", Color.ForestGreen)`, instead of outputting a "example" message on dark green, it appears with a dark blue, if a use Yellow or Red any color is shown.

**Comment by silkfire** [comment]
Could it be that Debian doesn't support ANSI codes in general? I haven't tested myself as I don't have a Debian environment to test with. If that is the case, then it's nothing that Pastel could do anything about, the console window itself must support (correct) colors.

**Comment by storm37000** [comment]
can confirm that it works fine on my Debian 10 server BUT does not work inside a screen terminal.  I think screen only supports the 256 color system.  Not sure if you could detect if it is running in screen and have some sort of compatibility mode to drop down to the 256 scheme.

**Comment by storm37000** [comment]
tmux can be made to support true color, if not it will approximate to the nearest 256 color space unlike screen which just shows white.
to enable true color in tmux do steps 4-6 https://www.homeonrails.com/2016/05/truecolor-in-gnome-terminal-tmux-and-neovim/

**Comment by silkfire** [comment]
It sounds a bit tricky if Pastel itself would approximate colors, and I'm not sure how to detect if it's running in a terminal with limited color support. It'd definitely affect performance too.

**Comment by storm37000** [comment]
yea, it was just a thought, the blame really goes onto the people who made the terminals to support it.

**Comment by silkfire** [comment]
If there's anyone who'd like to submit a fix through a PR, feel free to do so, all contributions are welcome.

**Comment by z3nth10n** [comment]
Let me try to PR this. This will take some days to me.

**Comment by silkfire** [comment]
@z3nth10n Have you made any progress on the PR?
