### ISSUE TITLE
How does this work in ssh sessions?

### ISSUE THREAD

**Issue by KoB-Kirito** [silkfire/Pastel#20]
It works fine when I run it locally, but when I put it on my linux server and connect via ssh, the colors get all meh.

Could you provide some tutorial on how to get that working?

**Comment by KoB-Kirito** [comment]
Okay, I can answer my own question~

Cmd/Powershell don't have 24-bit colors enabled by default -> Set in registry (HKEY_CURRENT_USER\Console) -> Create DWORD named VirtualTerminalLevel with value 1

Then I was using Screen, which seems to have problems with 24-bit colors. (Will come in version 5 I think?) -> I switched to tmux, which works fine.

**Comment by silkfire** [comment]
To be honest I haven't tried out all possible combinations of terminals out there, so I appreciate users doing that and providing feedback. Glad it worked out for you in the end.
