### ISSUE TITLE
Net Framework 4.7.2

### ISSUE THREAD

**Issue by PhillTV** [silkfire/Pastel#21]
Hey,
Could you add a download for .NET Framework 4.7.2>=?
All my Apps are written with fw 4.7.2 and i cant change the version bc i've created my one nuget Package only for version 4.7.2

Thx in advance

**Comment by silkfire** [comment]
Have you tried using the previous version, 1.3.2 with your project? If I remember correctly, .NET Standard 2.0 should be compatible with .NET Framework >=4.6.1.

**Comment by MokraCota** [comment]
Using .NET Framework 4.7.2 and using NuGet download returns:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Pastel 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by MokraCota** [comment]
We are talking about good old .NET Framework, not .NET Core or .NET 5.0.

**Comment by silkfire** [comment]
@MokraCota If you see my comment above, version 2.0.0 will definitely not work with .NET Framework. It is only meant to be compatible with .NET 5 at a minimum.
Try using v1.3.2 instead.

**Comment by MokraCota** [comment]
Why is Nuget showing me this version then? Is this an issue in Visual Studio NuGet? I don't see the 1.3.2 version at all in the NuGet GUI, I will try to load it via command.

**Comment by MokraCota** [comment]
OK, selecting 1.3.2 works fine.

**Comment by silkfire** [comment]
Yes, this seems to be a limitation with the NuGet Package Manager interface, it will show you all releases versions, regardless of compatibility with your projects.
