### ISSUE TITLE
long term supported .NET core 3.1 target

### ISSUE THREAD

**Issue by plv2** [silkfire/Pastel#22]
version 2.1.0 Multi-target .NET Standard 2.0 / .NET 5
please add also long term supported .NET core 3.1 target

**Comment by silkfire** [comment]
To be honest, targeting .NET Standard 2.0 should be enough for any .NET Core 3.1 app as well.

**Comment by plv2** [comment]
for core 3.0 yes but not for core 3.1
please, see https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.1.md
and https://docs.microsoft.com/fr-fr/dotnet/standard/net-standard

**Comment by silkfire** [comment]
Yes, as per the table on the page you linked, .NET Standard 2.0 is supported from .NET Core 2.0 and above. That means .NET Core 3.1 definitely supports it.

**Comment by plv2** [comment]
May be. What I have experimented today is that pastel v2.1.0 fail on nuget with core 3.1 and success with core 3.0 net 4.8 and net 5.0 projects. May be there is a problem some where else but probably not.
As we will move asap from core 3.1 to net 5.0 this problem will be solved this way.

for now we turn around this problem in *.csproj via:
```
<TargetFrameworks>net5.0-windows;netcoreapp3.1</TargetFrameworks>
. . . . .
<PackageReference Include="Pastel" Version="1.3.2" Condition="$(TargetFramework.StartsWith('netcoreapp3'))" />
<PackageReference Include="Pastel" Version="2.1.0" Condition="$(TargetFramework.StartsWith('net5'))" />
```
Any way, thanks for your time and this nice lib.

**Comment by silkfire** [comment]
That is strange indeed. What is the actual error you're getting?
