### ISSUE TITLE
Number colorization problem

### ISSUE THREAD

**Issue by AIUbi** [silkfire/Pastel#27]
HI have issue with numbers. 
I'm trying to make syntax highlighting, with braces works fine but not with numbers. 
This is how I use pastel for number string
`_numbers.Replace(message, x => (@x.Value).Pastel(UITheme.SyntaxNumberFg));`
This is a regular expressions for numbers
`
private static readonly RegexOptions _regexOptions = RegexOptions.IgnoreCase | RegexOptions.Compiled | RegexOptions.CultureInvariant;
private Regex _numbers = new Regex(@"[0-9]+", _regexOptions);
`
And this  is what happens if I enter regular number into console.
![image](https://user-images.githubusercontent.com/6118467/221524088-fc43862d-b9e3-4030-b315-16515ee4216a.png)
Any advice about that?

**Comment by silkfire** [comment]
Could you print the full string you're trying to colorize?

**Comment by AIUbi** [comment]
> Could you print the full string you're trying to colorize?

Sure, as you can see on screenshot is a pure number.
This is input string
`
99999999999999999
`
And this one is output after regex
`
[38;2;170;255;30m[[0m38;2;0;155;255m99999999999999999[38;2;170;255;30m[[0m0m
`
Screenshot of output string in NP++
![image](https://user-images.githubusercontent.com/6118467/221527931-fb2356e9-b017-4c4d-a17b-0b1d54a62665.png)

**Comment by AIUbi** [comment]
Additional details it works fine with braces
![image](https://user-images.githubusercontent.com/6118467/221528756-81eb349c-a5fb-4fb2-ad61-8cfe0ce469cd.png)
![image](https://user-images.githubusercontent.com/6118467/221529166-7af682fa-361c-4d30-bab1-1ebdd053bcde.png)
Input
`
Braces test <a> [some] {string} withsymbols !
`
Output
`
Braces test [38;2;170;255;30m<[0ma[38;2;170;255;30m>[0m [38;2;170;255;30m[[0msome[38;2;170;255;30m][0m [38;2;170;255;30m{[0mstring[38;2;170;255;30m}[0m withsymbols [38;2;170;255;30m![0m
`

**Comment by AIUbi** [comment]
Topic can be closed, problem in regex, now it works "fine" still have problems.
The problem is in replacement, so if some Regex partially fit Pastel style Regex would broke the Pastel scheme.
Solution - iteratively walk through text and if some match happens apply Regex and save result in buffered string.
![image](https://user-images.githubusercontent.com/6118467/221540835-09caa6dd-fd4a-486d-907d-00ecf4ed91df.png)

**Comment by silkfire** [comment]
Yea, Pastel relies on ANSI codes to work, so if your string contains that it can pick up on that and mess things up.

**Comment by AIUbi** [comment]
> Yea, Pastel relies on ANSI codes to work, so if your string contains that it can pick up on that and mess things up.

Ty for your time
