### ISSUE TITLE
Will it work on Linux?

### ISSUE THREAD

**Issue by Morasiu** [silkfire/Pastel#3]
Hi!

I wanted to include your cute lib in my project, but... 

since you are using kernel32.dll it will probably don't work on Linux and Mac.

Am I right?

**Comment by silkfire** [comment]
I see how those DLL attributes can make someone think that it only was meant to run on Windows machines, but on the contrary, those attributes are actually only required to activate the feature on the Windows platform. In Linux, terminals should understand the ANSI codes already by default.

See this sample below:

![example-linux](https://user-images.githubusercontent.com/1554615/52055712-774af500-2560-11e9-846b-271b738d5689.png)

**Comment by Morasiu** [comment]
Awesome! Great work 👍
