### ISSUE TITLE
(r,g,b) overload method?

### ISSUE THREAD

**Issue by AnalogFeelings** [silkfire/Pastel#32]
As seen in the title, this would skip the step of parsing the hex string or referencing System.Drawing which isn't ideal for cross platform.

**Comment by silkfire** [comment]
I'm aware that parts of the `System.Drawing` namespace [isn't cross platform](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#affected-apis), but `Color` specifically is not affected (as it's a simple struct).

**Comment by AnalogFeelings** [comment]
> I'm aware that parts of the `System.Drawing` namespace [isn't cross platform](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#affected-apis), but `Color` specifically is not affected (as it's a simple struct).

Including an entire assembly just for a Color struct feels kind of excessive, though

**Comment by silkfire** [comment]
It's part of the framework, just like `System.Console` or any other type in the `System` namespace. Also I like the reasoning around the `Color` type as it makes it easier to identify colors.

![image](https://github.com/silkfire/Pastel/assets/1554615/001bff82-32d1-45b8-bb34-6acd0a95de77)
