### ISSUE TITLE
I need a way to disable environment detection !

### ISSUE THREAD

**Issue by TheYggdrazil** [silkfire/Pastel#33]
Hello,

I used to have colors in my Jenkins logs, using the AnsiColor plugin for Jenkins. This is not the case anymore, and I realized this is due to the addition of the environment detection in your latest releases.

Would it be possible to bypass this and force the colors ?

**Comment by TheYggdrazil** [comment]
@JKamsker

**Comment by silkfire** [comment]
Absolutely, I was thinking of adding a global variable to disable environment checking. I'll let you know when it's implemented.

**Comment by silkfire** [comment]
@TheYggdrazil The release is out https://github.com/silkfire/Pastel/releases/tag/v5.1.0

Updated documentation as well @ https://github.com/silkfire/Pastel?tab=readme-ov-file#cicd-environments

**Comment by TheYggdrazil** [comment]
Thanks ! :)
