### ISSUE TITLE
Foreground/Background properties

### ISSUE THREAD

**Issue by marss72** [silkfire/Pastel#34]
I don't know how this could be implemented, but I would really appreciate a library function to set a default foreground or background color. This could be useful - especially when the user has a different default console background (setting the PastelBg every time makes code less readable and it doesn't look good).

Maybe, `ConsoleExtensions.Foreground = Color.White`. It could also be a method, like `ConsoleExtensions.Background(Color.Black)` to support both Color and ConsoleColor.

Also, just a small detail. I understand it will probably be hard to implement in this existing code, but instead of converting ConsoleColor to Color, we could just use the ANSI to show the console-defined color, so like `\x1b[31mHello` would be for red foreground (https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#color-codes). This could fix the problem when the terminal has a white background for example - instead of converting the color into RGB, we will use the console-defined color.

**Comment by silkfire** [comment]
You can already set the foreground/background color of the console natively with the `Console.ForegroundColor` or `Console.BackgroundColor` properties, respectively.

Regarding your second request, I might be able to implement it by adding a flag to the `ConsoleColor` overloads that allow you to override the default behavior.

**Comment by marss72** [comment]
> You can already set the foreground/background color of the console natively with the `Console.ForegroundColor` or `Console.BackgroundColor` properties, respectively.

I can, but this doesn't support ANSI colors — so if I use Pastel with RGB colors on the foreground and set Black as a background, the contrast might be bad as Black will become White in the console settings, but RGB will stay, so, for example, white text (with Pastel) in white theme console will not be visible at all.

**Comment by silkfire** [comment]
The thing is, I want to avoid Pastel to keep state as it is mainly supposed to be used by calling extension methods. The Enabled/Disabled flags are the only exception.
