### ISSUE TITLE
24-bit colors not supported in GitLab CI

### ISSUE THREAD

**Issue by Pipelynx** [silkfire/Pastel#35]
I wrote a C# program that's being run in a GitLab CI job.
In a Powershell Terminal, the colors work perfectly, but in the CI job they do not, even though I see the escape codes in the raw log.

I tried to use the escape codes with the limited number of colors like `\e[31m`, and that does work.

Is there any way to use only "numbered" colors, instead of using RGB values like `\e[38;2;255;255;255m`?

**Comment by silkfire** [comment]
I have always intended Pastel to use the ANSI-color syntax, that was one of the reason I created it as I only saw the old-style syntax in other libraries at the time.

Perhaps [Crayon](https://github.com/riezebosch/crayon) would suit your needs?

**Comment by Pipelynx** [comment]
Yes, Crayon solved the problem!

Your library is **awesome** too though, thanks for your work!

**Comment by silkfire** [comment]
No worries, sometimes you simply have to use the right tool for the job. I appreciate your comment 😊
