### ISSUE TITLE
[Suggestion] Add extension for `ReadOnlySpan<char>`

### ISSUE THREAD

**Issue by slxdy** [silkfire/Pastel#36]
If I understand the source correctly, the internal pastel function already reads the input string as a Span.
It would be great to be able to pass an existing Span to the function, for example if the Span was made from an unmanaged unicode string pointer, just to avoid that little extra allocation :)

**Comment by silkfire** [comment]
This is a great suggestion! There's no reason I haven't added it yet except for the simple fact that I haven't had a use case for it.

I've now refactored all methods to use `ReadOnlySpan<char>` by default and am referring the original `string`-based extension methods there by use of `AsSpan()`.

The feature is out in [v5.2.1](https://github.com/silkfire/Pastel/releases/tag/v5.2.1)

**Comment by slxdy** [comment]
Wow, thanks for the quick update!
