### ISSUE TITLE
I love your work thank you so much

### ISSUE THREAD

**Issue by verd0s** [silkfire/Pastel#4]
So I love this little library you made but one thing triggered me and that was my ocd I cleaned up the code https://gist.github.com/verd0s/f35fedeab668e618e41fee44f6753e85 I just hate when stuff goes off the side also changed a little bit because their was boxing allocations on the Color bytes when converting them to strings which can cause alot of overhead if your printing alot to your console

**Comment by silkfire** [comment]
I am not sure about what kind of improvement your code actually brings, to be honest. Closing this (non-)issue for now.

**Comment by verd0s** [comment]
I added gradient support
