### ISSUE TITLE
Nested Coloring

### ISSUE THREAD

**Issue by Nucs** [silkfire/Pastel#6]
Greetings,
Consider the following line:
```C#
Console.WriteLine($"abc {"123".Pastel(Color.Green)} efg".Pastel(Color.IndianRed));
```
This prints: ![image](https://user-images.githubusercontent.com/649919/54814493-8add2700-4c98-11e9-9e61-e91715004f44.png)
While 'efg' is expected to be also red.

Thanks, Eli.

**Comment by silkfire** [comment]
This problem is due to the way Pastel wraps the color codes. Every string ends in a termination code, rendering everything afterwards without color, up until a new begin color character.
I'll see if I can figure out a way to solve this, but for now I would advise to color every part explicitly:

`$"{"abc".Pastel(Color.IndianRed)}{"123".Pastel(Color.Green)} {"efg".Pastel(Color.IndianRed)"`

**Comment by mattiasnordqvist** [comment]
Here is a failing test, I think 🤔 

```
[Fact]
public void Test2()
{
    int red1 = 1, green1 = 1, blue1 = 1;
    int red2 = 2, green2 = 2, blue2 = 2;
    string output = $"a{"b".Pastel(Color.FromArgb(red2, green2, blue2))}c".Pastel(Color.FromArgb(red1, green1, blue1));

    var expected = "\u001b[38;2;1;1;1ma\u001b[0m\u001b[38;2;2;2;2mb\u001b[0m\u001b[38;2;1;1;1mc\u001b[0m";

    Assert.Equal(expected, output); //actual = \u001b[[38;2;1;1;1ma\u001b[[38;2;2;2;2mb\u001b[[0mc\u001b[[0m
}

```

**Comment by mattiasnordqvist** [comment]
Or you could use this which I just created. Not supporting background colors yet and could probably be a polished a bit but it works nice i think.

```csharp
var example = new ArtisticString("abc 123 efg", Color.IndianRed);
new ArtisticPainter()
    .BeCreativeWith(new ArtisticRegexBrush("[0-9]", Color.Green))
    .Unleash(example);
Console.WriteLine(example);
```
https://github.com/mattiasnordqvist/Artistic-Pastel-Painter
https://www.nuget.org/packages/ArtisticPastelPainter/0.1.0

**Comment by silkfire** [comment]
@mattiasnordqvist Wow, that is really creative! I feel really humbled that you've put in the effort to create something of you own, inspired by my own library, and also by a fellow Swede :)

I think I have a possible solution in store, I just need to find the time to implement it; hopefully this coming week.

**Comment by silkfire** [comment]
@mattiasnordqvist Finally I got some time to work on this issue! I'm now quite confident that I've solved it. The new version should be available on NuGet shortly.

**Comment by silkfire** [comment]
@Nucs @mattiasnordqvist If you're happy with how it works now, I could close this issue as resolved.

**Comment by Nucs** [comment]
Thank you, working just fine.
