### ISSUE TITLE
Underline, Bold

### ISSUE THREAD

**Issue by mattiasnordqvist** [silkfire/Pastel#8]
For completeness, allow underline and bold text decorations. What do you think? Not that I need it... just putting it out there.

**Comment by silkfire** [comment]
This feature has been requested before (see https://github.com/silkfire/Pastel/pull/5). Right now I'm happy with keeping the library as tiny as possible, and its main purpose is to provide colors only, not any formatting. This of course may change in the future, but I have no such plans today.
