### ISSUE TITLE
.NET Core Configuration Section for Pastel Color Schemes

### ISSUE THREAD

**Issue by jzabroski** [silkfire/Pastel#9]
Most people use green, red, yellow, white and gray ForegroundColor on a black BackgroundColor.  Once you start changing some of these, as well as their default terminal color theme, it gets _crazy_!

The simplest configuration would let people control basic "streams":

- Debug
- Verbose
- Warning
- Error

The rational for these streams is that these are the ones supported by Windows PowerShell.

**Comment by GabrielBBF** [comment]
I'm not sure I'm following you. Could you give examples / post pictures of what you'd like to achieve?

**Comment by silkfire** [comment]
I'm not sure I'm following you. Could you give examples / post pictures of what you'd like to achieve?

**Comment by jzabroski** [comment]
Sure.

In PowerShell, you can edit your $PROFILE to contain lines like:

```powershell
$host.PrivateData.ErrorForegroundColor = 'White'
$host.PrivateData.ErrorBackgroundColor = 'Blue'
```

It would be great if this was part of an `appSettings.Color.json` file:

```javascript
{
  "console.colors": {
    "error": { "foreground": "white", "background": "blue" }
  }
}
```

**Comment by silkfire** [comment]
Pastel works by activating color on explicit calls to its methods, how would it possibly know when to color a specific type of message?

**Comment by mattiasnordqvist** [comment]
I think pastel should stay "environment-agnostic". My opinion is that these kind of configurations belong in the consumer.

**Comment by GabrielBBF** [comment]
@mattiasnordqvist That has been my philosophy as well, the only exception being the `NO_COLOR` support. This functionality feels a bit too obscure and and unclear according to me to implement.

**Comment by silkfire** [comment]
@mattiasnordqvist That has been my philosophy as well, the only exception being the `NO_COLOR` support. This functionality feels a bit too obscure and unclear according to me to implement.

**Comment by jzabroski** [comment]
OK, I'll close it.
